/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package responsi.view;
import javax.swing.JOptionPane;
import responsi.controller.pabrikcontroller;
import javax.swing.JTable;

/**
 *
 * @author Lenovo
 */
public class pabrikView extends javax.swing.JFrame {

    /**
     * Creates new form pabrikView
     */
    pabrikcontroller c;
    public pabrikView(pabrikcontroller c) {
        initComponents();
        this.c= c;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelproduk = new javax.swing.JLabel();
        jTextFieldproduk = new javax.swing.JTextField();
        jLabelunit = new javax.swing.JLabel();
        jLabeljam = new javax.swing.JLabel();
        jTextFieldunit = new javax.swing.JTextField();
        jTextFieldjam = new javax.swing.JTextField();
        jLabeltenaga = new javax.swing.JLabel();
        jTextFieldtenaga = new javax.swing.JTextField();
        jLabelbiaya = new javax.swing.JLabel();
        jTextFieldbiaya = new javax.swing.JTextField();
        jButtoncreate = new javax.swing.JButton();
        jButtonedit = new javax.swing.JButton();
        jButtondelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabledatapabrik = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelproduk.setText("Nama Produk");

        jLabelunit.setText("Jumlah Unit");

        jLabeljam.setText("Jam Kerja");

        jLabeltenaga.setText("Jumlah Tenaga Kerja");

        jTextFieldtenaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtenagaActionPerformed(evt);
            }
        });

        jLabelbiaya.setText("Biaya Bahan Baku");

        jTextFieldbiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldbiayaActionPerformed(evt);
            }
        });

        jButtoncreate.setText("Create");
        jButtoncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncreateActionPerformed(evt);
            }
        });

        jButtonedit.setText("Edit");
        jButtonedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoneditActionPerformed(evt);
            }
        });

        jButtondelete.setText("Delete");
        jButtondelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondeleteActionPerformed(evt);
            }
        });

        jTabledatapabrik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabledatapabrik);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtoncreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonedit)
                        .addGap(18, 18, 18)
                        .addComponent(jButtondelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabeltenaga)
                            .addComponent(jLabeljam)
                            .addComponent(jLabelunit)
                            .addComponent(jLabelproduk)
                            .addComponent(jLabelbiaya))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldjam, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(jTextFieldtenaga)
                            .addComponent(jTextFieldunit)
                            .addComponent(jTextFieldproduk)
                            .addComponent(jTextFieldbiaya))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelproduk)
                            .addComponent(jTextFieldproduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelunit)
                            .addComponent(jTextFieldunit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeljam)
                            .addComponent(jTextFieldjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabeltenaga)
                            .addComponent(jTextFieldtenaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelbiaya)
                            .addComponent(jTextFieldbiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtoncreate)
                            .addComponent(jButtonedit)
                            .addComponent(jButtondelete)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldtenagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldtenagaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldtenagaActionPerformed

    private void jTextFieldbiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldbiayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldbiayaActionPerformed

    private void jButtoncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncreateActionPerformed
        String produk = jTextFieldproduk.getText().trim();
        String unittext = jTextFieldunit.getText().trim();
        String jamKerjatext = jTextFieldjam.getText().trim();
        String tenagaKerjatext = jTextFieldtenaga.getText().trim();
        String bahanBakutext = jTextFieldbiaya.getText().trim();
        
        if(produk.isEmpty() || unittext.isEmpty() || jamKerjatext.isEmpty()||tenagaKerjatext.isEmpty()|| bahanBakutext.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Semua Harus diisi", "Input belum lengkap", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        
        int unit =Integer.parseInt(unittext);
        int jamKerja =Integer.parseInt(jamKerjatext);
        int tenagaKerja =Integer.parseInt(tenagaKerjatext);
        int bahanBaku =Integer.parseInt(bahanBakutext);
        
        c.tambah(produk, unit, jamKerja, tenagaKerja, bahanBaku);
        jTextFieldproduk.setText("");
        jTextFieldunit.setText("");
        jTextFieldjam.setText("");
        jTextFieldtenaga.setText("");
        jTextFieldbiaya.setText("");
    }//GEN-LAST:event_jButtoncreateActionPerformed

    private void jButtondeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondeleteActionPerformed
        int selectedRow= jTabledatapabrik.getSelectedRow();
        
        if(selectedRow != 1){
            int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah data ini akan dihapus?", "Konfirmasi Hapus", 
                    JOptionPane.YES_NO_OPTION);
            if(konfirmasi== JOptionPane.YES_OPTION){
                int id= c.getDataList().get(selectedRow).getId();
                c.hapus(id);
            }else{
            JOptionPane.showConfirmDialog(this, "Pilih data yang ingin dihapus");
            }
        }
    }//GEN-LAST:event_jButtondeleteActionPerformed

    private void jButtoneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoneditActionPerformed
        int selectedRow= jTabledatapabrik.getSelectedRow();
        
        if(selectedRow != 1){
        String produk = jTextFieldproduk.getText().trim();
        String unittext = jTextFieldunit.getText().trim();
        String jamKerjatext = jTextFieldjam.getText().trim();
        String tenagaKerjatext = jTextFieldtenaga.getText().trim();
        String bahanBakutext = jTextFieldbiaya.getText().trim();
        
        if(produk.isEmpty() && unittext.isEmpty() && jamKerjatext.isEmpty()&& tenagaKerjatext.isEmpty()&& bahanBakutext.isEmpty()){
            int id= c.getDataList().get(selectedRow).getId();
            
            int unit =Integer.parseInt(jTabledatapabrik.getValueAt(selectedRow,0).toString());
            int jamKerja =Integer.parseInt(jTabledatapabrik.getValueAt(selectedRow,0).toString());
            int tenagaKerja =Integer.parseInt(jTabledatapabrik.getValueAt(selectedRow,0).toString());
            int bahanBaku =Integer.parseInt(jTabledatapabrik.getValueAt(selectedRow,0).toString());
            
            c.edit(id, produk, unit, jamKerja, tenagaKerja, bahanBaku);
            c.refreshTable();
            jTextFieldproduk.setText("");
            jTextFieldunit.setText("");
            jTextFieldjam.setText("");
            jTextFieldtenaga.setText("");
            jTextFieldbiaya.setText("");
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "Semua Harus diisi", "Input belum lengkap", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }else{
      JOptionPane.showConfirmDialog(this, "Pilih data yang ingin dihapus");  
         }
        
    }//GEN-LAST:event_jButtoneditActionPerformed

    public JTable getjTablePabrik(){
        return jTabledatapabrik;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoncreate;
    private javax.swing.JButton jButtondelete;
    private javax.swing.JButton jButtonedit;
    private javax.swing.JLabel jLabelbiaya;
    private javax.swing.JLabel jLabeljam;
    private javax.swing.JLabel jLabelproduk;
    private javax.swing.JLabel jLabeltenaga;
    private javax.swing.JLabel jLabelunit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabledatapabrik;
    private javax.swing.JTextField jTextFieldbiaya;
    private javax.swing.JTextField jTextFieldjam;
    private javax.swing.JTextField jTextFieldproduk;
    private javax.swing.JTextField jTextFieldtenaga;
    private javax.swing.JTextField jTextFieldunit;
    // End of variables declaration//GEN-END:variables
}
